---

- name: Create temporary working directory
  file:
    path: /tmp/micromambda
    state: directory

- name: Download micromamba to /tmp/micromamba/
  get_url:
    url: "https://micro.mamba.pm/api/micromamba/linux-64/{{ micromamba_version }}"
    dest: /tmp/micromamba/micromamba.tar.bz2
    checksum: "{{ micromamba_download_checksum }}"

- name: Extract micromamba executable
  unarchive:
    src: /tmp/micromamba/micromamba.tar.bz2
    dest: /tmp/micromamba

- name: Install micromamba executable
  become: true
  copy:
    src: /tmp/micromamba/bin/micromamba
    dest: /usr/local/bin/micromamba
    mode: 0555

- name: Remove temporary files
  file:
    state: absent
    path: /tmp/micromamba
