---

- name: Remove previous environment if it exists
  file:
    state: absent
    path: "{{ lookup('env','HOME') }}/micromamba/envs/{{ micromamba_env_name }}"

- name: Create micromamba environment
  shell: "micromamba create -y -n {{ micromamba_env_name }} python={{ python_version }} -c conda-forge"

- name: Initialize micromamba environment
  shell: |
    eval "$(micromamba shell hook)"
    micromamba activate {{ micromamba_env_name | quote }}
    pip install {{ item | quote }}
  loop: "{{ pip_install }}"
  environment:
    PATH: "{{ lookup('env','HOME') }}/micromamba/envs/{{ micromamba_env_name }}/bin:{{ ansible_env.PATH }"
