---

- name: Ensure path for micromamba install exists
  file:
    path: /opt/oulib/micromamba/bin
    state: directory

- name: Create micromamba user
  user:
    name: micromamba
    comment: Service account for managing python environments and versions

- name: Create temporary working directory
  file:
    path: /tmp/micromamba
    state: directory

- name: Download micromamba to /tmp/micromamba/
  get_url:
    url: "https://micro.mamba.pm/api/micromamba/linux-64/{{ mamba_micromamba_version }}"
    dest: /tmp/micromamba/micromamba.tar.bz2
    checksum: "{{ mamba_micromamba_download_checksum }}"

- name: Extract micromamba executable
  unarchive:
    src: /tmp/micromamba/micromamba.tar.bz2
    dest: /tmp/micromamba/
    remote_src: true

- name: Install micromamba executable
  become: true
  copy:
    src: /tmp/micromamba/bin/micromamba
    dest: /opt/oulib/micromamba/bin
    owner: root
    group: wheel
    mode: 0555
    remote_src: true

- name: Remove temporary files
  file:
    state: absent
    path: /tmp/micromamba
